[package]
name = "polygondb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
lto = "fat"
codegen-units = 1

[profile.dev.package.simple-websockets]
opt-level = 2

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
jsonptr = "*"
json_value_remove = "*"
mimalloc = { version = "0.1.17", default-features = false }
simple-websockets = "*"
simd-json = "0.12.0"
ajson = "0.3.1"
