FROM        --platform=$TARGETOS/$TARGETARCH alpine:latest

LABEL       author="Michael Parker" maintainer="parker@pterodactyl.io"

LABEL       org.opencontainers.image.source="https://github.com/JewishLewish/PolygonDB"
LABEL       org.opencontainers.image.licenses=MIT

RUN         apk update && apk add bash